# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(KETCAU_AUTH_MAGIC)%'
    default_locale: '%locale%'
    handle_all_throwables: true
    translator:
        fallback: ['%locale%']
    csrf_protection: { enabled: true }
    http_method_override: true
    trusted_hosts: ~
    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
#        handler_id: 'Ketcau\Session\Storage\Handler\SameSiteNoneCompatSessionHandler'
        save_path: '%kernel.project_dir%/var/session/%kernel.environment%'
        name: '%env(KETCAU_COOKIE_NAME)%'
        cookie_lifetime: '%env(KETCAU_COOKIE_LIFETIME)%'
        gc_maxlifetime: '%env(KETCAU_GC_MAXLIFETIME)%'
        cookie_httponly: true

    esi: { enabled: true }
    fragments: { enabled: true }
    php_errors:
        log: true
    assets:
        base_path: '/template/%ketcau.theme%'
        packages:
            admin:
                base_path: '/template/admin'
            save_image:
                base_path: '/upload/save_image'
            plugin:
                base_path: '/plugin'
            install:
                base_path: '/template/install'
            temp_image:
                base_path: '/upload/temp_image'
            user_data:
                base_path: '/user_data'
            bundle:
                base_path: '/bundle'
    cache:
        prefix_seed: ketcau
    ide: ~
    validation: { enable_annotations: true }

    serializer:
        mapping:
            paths: ['%kernel.project_dir%/config/packages/serializer']
