parameters:
  ketcau_nav:
    product:
      name: admin.product.product_management
      icon: fa-cube
      children:
        product_master:
          name: admin.product.product_list
          children:
            seller_master:
              name: admin.product.seller_master
              url: admin_homepage
    customer:
      name: admin.customer.customer_management
      icon: fa-user
      children:
        seller:
          name: admin.customer.seller_management
          children:
            seller_attestation:
              name: admin.customer.seller_attestation
              url: admin_homepage
        buyer:
          name: admin.customer.buyer_management
          children:
            buyer_attestation:
              name: admin.customer.buyer_attestation
              url: admin_homepage
    content:
      name: admin.content.contents_management
      icon: fa-file-text
      children:
        layout:
          name: admin.content.layout_management
          url: admin_content_layout
        page:
          name: admin.content.page_management
          url: admin_content_page
        block:
          name: admin.content.block_management
          url: admin_content_block
        cache:
          name: admin.content.cache_management
          url: admin_content_cache
        maintenance:
          name: admin.content.maintenance_management
          url: admin_content_maintenance
    setting:
      name: admin.setting
      icon: fa-cog
      children:
        system_index:
          name: admin.setting.system.system_info
          url: admin_setting_system_info
