version: '3'

volumes:
  mysql-database:
    driver: local

services:
  ketcau:
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://dbuser:secret@mysql/ketcau"
      DATABASE_SERVER_VERSION: 5.7
      DATABASE_CHARSET: 'utf8mb4'

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-database:/var/lib/mysql
      - ./dockerfile/mysql/grant_to_dbuser.sql:/docker-entrypoint-initdb.d/grant_to_dbuser.sql
    ports:
      - 3306:3306
    networks:
      - backend
    healthcheck:
      test: mysqladmin ping
      interval: 3s
      timeout: 3s
      retries: 3
