version: "3"

networks:
  backend:
    driver: bridge

services:
  ketcau:
    build: ./dockerfile/apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    networks:
      - backend

#  php-fpm:
#    build: ./dockerfile/php-fpm
#    ports:
#      - "9000:9000"
#    volumes:
#      - ./:/var/www
#    environment:
#      APP_ENV: "dev"
#      APP_DEBUG: 1
#    networks:
#      - backend

  nuxt3:
    build: ./dockerfile/nuxt3
    ports:
      - "3000:3000"
    volumes:
      - ./app/nuxt/pocket:/home/app
    networks:
      - backend

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1880:1080"
      - "1825:1025"
    networks:
      - backend

